name: Linux build
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash -l {0}
jobs:
  build:
    runs-on: ubuntu-latest
    name: '${{ matrix.sys.compiler }} ${{ matrix.sys.version }} - ${{ matrix.sys.flags }}'
    strategy:
      matrix:
        sys:
          - { compiler: 'gcc',   version: '13', flags: 'enable_xtl_complex' }
          - { compiler: 'gcc',   version: '14', flags: 'avx' }
          - { compiler: 'gcc',   version: '12', flags: 'i386' }
          - { compiler: 'gcc',   version: '13', flags: 'avx512pf' }
          - { compiler: 'gcc',   version: '13', flags: 'avx512vbmi' }
          - { compiler: 'gcc',   version: '14', flags: 'avx512vbmi2' }
          - { compiler: 'gcc',   version: '13', flags: 'avx512vnni' }
          - { compiler: 'gcc',   version: '14', flags: 'avx512bf16' }
          - { compiler: 'gcc',   version: '14', flags: 'x86-64' }
          - { compiler: 'gcc',   version: '14', flags: 'x86-64-v2' }
          - { compiler: 'gcc',   version: '14', flags: 'x86-64-v3' }
          - { compiler: 'gcc',   version: '14', flags: 'x86-64-v4' }
          - { compiler: 'clang', version: '16', flags: 'enable_xtl_complex' }
          - { compiler: 'clang', version: '17', flags: 'avx' }
          - { compiler: 'clang', version: '18', flags: 'x86-64' }
          - { compiler: 'clang', version: '18', flags: 'x86-64-v2' }
          - { compiler: 'clang', version: '18', flags: 'x86-64-v3' }
          - { compiler: 'clang', version: '18', flags: 'x86-64-v4' }
    steps:
    - name: Setup compiler
      if: ${{ matrix.sys.compiler == 'gcc' }}
      run: |
        GCC_VERSION=${{ matrix.sys.version }}
        sudo apt-get update
        sudo apt-get --no-install-suggests --no-install-recommends install g++-$GCC_VERSION
        sudo dpkg --add-architecture i386
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get --no-install-suggests --no-install-recommends install gcc-$GCC_VERSION-multilib g++-$GCC_VERSION-multilib linux-libc-dev:i386
        CC=gcc-$GCC_VERSION
        echo "CC=$CC" >> $GITHUB_ENV
        CXX=g++-$GCC_VERSION
        echo "CXX=$CXX" >> $GITHUB_ENV
    - name: Setup compiler
      if: ${{ matrix.sys.compiler == 'clang' }}
      run: |
        LLVM_VERSION=${{ matrix.sys.version }}
        sudo apt-get update || exit 1
        sudo apt-get --no-install-suggests --no-install-recommends install clang-$LLVM_VERSION || exit 1
        sudo apt-get --no-install-suggests --no-install-recommends install g++ g++-multilib || exit 1
        sudo ln -s /usr/include/asm-generic /usr/include/asm
        CC=clang-$LLVM_VERSION
        echo "CC=$CC" >> $GITHUB_ENV
        CXX=clang++-$LLVM_VERSION
        echo "CXX=$CXX" >> $GITHUB_ENV
    - name: Checkout xsimd
      uses: actions/checkout@v3
    - name: Install mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
    - name: Setup SDE
      if: startswith(matrix.sys.flags, 'avx512')
      run: sh install_sde.sh
    - name: Configure build
      env:
        CC: ${{ env.CC }}
        CXX: ${{ env.CXX }}
      run: |
        if [[ '${{ matrix.sys.flags }}' == 'enable_xtl_complex' ]]; then
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DENABLE_XTL_COMPLEX=ON"
        fi
        if [[ '${{ matrix.sys.flags }}' == 'avx' ]]; then
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DTARGET_ARCH=sandybridge"
        fi
        if [[ '${{ matrix.sys.flags }}' == 'avx512' ]]; then
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DTARGET_ARCH=skylake-avx512"
        fi
        if [[ '${{ matrix.sys.flags }}' == 'avx512pf' ]]; then
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DTARGET_ARCH=knl"
        fi
        if [[ '${{ matrix.sys.flags }}' == 'avx512vbmi' ]]; then
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DTARGET_ARCH=cannonlake"
        fi
        if [[ '${{ matrix.sys.flags }}' == 'avx512vbmi2' ]]; then
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DTARGET_ARCH=icelake-server"
        fi
        if [[ '${{ matrix.sys.flags }}' == 'avx512vnni' ]]; then
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DTARGET_ARCH=knm"
        fi
        if [[ '${{ matrix.sys.flags }}' == 'avx512bf16' ]]; then
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DTARGET_ARCH=cooperlake"
        fi
        if [[ '${{ matrix.sys.flags }}' == 'i386' ]]; then
          CXX_FLAGS="$CXX_FLAGS -m32"
        fi
        if [[ '${{ matrix.sys.flags }}' =~ ^x86-64(-v[234])?$ ]]; then
          CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DTARGET_ARCH=${{ matrix.sys.flags }}"
        fi    
        CMAKE_EXTRA_ARGS="$CMAKE_EXTRA_ARGS -DXSIMD_ENABLE_WERROR=ON"

        # Cheap way of spotting uninitialized read
        CXX_FLAGS="$CXX_FLAGS -ftrivial-auto-var-init=pattern"

        mkdir _build
        cd _build
        cmake  .. -DBUILD_TESTS=ON \
                  -DBUILD_BENCHMARK=ON \
                  -DBUILD_EXAMPLES=ON \
                  -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_C_COMPILER=$CC \
                  -DCMAKE_CXX_COMPILER=$CXX \
                  $CMAKE_EXTRA_ARGS \
                  -DCMAKE_CXX_FLAGS='$CXX_FLAGS' \
                  -G Ninja
    - name: Build
      run: ninja -C _build
    - name: Test
      run: |
        cd _build
        cd test
        if [[ '${{ matrix.sys.flags }}' =~ avx512|x86-64-v4 ]]; then
          ../../sde-external-9.48.0-2024-11-25-lin/sde64 -tgl -- ./test_xsimd
        else
          ./test_xsimd
        fi
